### ISSUE TITLE
Sitecore 9.2 support

### ISSUE THREAD

**Issue by butterflycoder333** [mtelligent/SitecoreWebPushNotifications#1]
Hi there,
We were hoping to make use of your plugin, but are only on 9.2. Do you know if anyone has forked your repo to get it playing nicely in the 9.2 version of Sitecore? And / Or if you know of any major gotchas if we were to try and make it compatible with the earlier version? Super keen on this package, but not quite in a spot to do an upgrade currently. 
Thanks a bunch

**Comment by mtelligent** [comment]
I'm not aware of anyone who has forked the project to support Sitecore 9.2, but the module is pretty new and I'm hoping it will get more attention after my on demand session at Sitecore Symposium next week. 

That being said, I'm not aware of any issues or concerns that would cause problems on 9.2. Would assume you just need to recompile against the right nuget dependencies and .Net Version. I would fork from the Sitecore93 branch as a starting point. If you have any issues, let me know.
